language: c

branches:
  only:
    - master
    - develop
    - /^feature\/\w+/

install:
  - sudo apt-get install -q wget bsdtar
  - sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" >> /etc/apt/sources.list.d/virtualbox.list'
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update -q
  - sudo uname -r
  - sudo apt-get install -q virtualbox-5.0 linux-headers-3.13.0-63-generic
  - sudo /sbin/rcvboxdrv setup
  - wget http://download.virtualbox.org/virtualbox/5.0.20/Oracle_VM_VirtualBox_Extension_Pack-5.0.20-106931.vbox-extpack
  - sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-5.0.20-106931.vbox-extpack
  - wget -q https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip -O- | sudo bsdtar -C /usr/local/bin -xf-

script:
  - PACKER_LOG=1 packer build packer.json
