language: c
services:
  - docker

branches:
  only:
    - master
    - develop
    - /^feature\/\w+/
env:
  global:
    - DOCKER_IMAGE=blacklabelops/virtualbox

script:
  - docker run -v $(pwd):$(pwd) -w $(pwd) -e VAGRANT_TOKEN $DOCKER_IMAGE /bin/sh -c 'packer build packer.json'
